classDiagram
    namespace Gridspace {
        class Grid~E~
        class IndexedGrid~E~
        class UIGrid~E~
        class GridPoint

        class Indexer
        class ZigZagIndexer
        class SpiralIndexer
        class MortonIndexer
    }
        class GridPoint {
            getSideNeighbors() GridPoint[4]
            getDiagonalNeighbors() GridPoint[4]
            getNeighbors() GridPoint[8]
            getNeighbors(int range) GridPoint[]
        }
        GridPoint --|> Point

        class Grid~E~ {
            <<Interface>>
            add(GridPoint Gridpoint, E obj)
            add(int x, int y, E obj)
            get(GridPoint Gridpoint)
            get(int x, int y)
            remove(GridPoint Gridpoint)
            remove(int x, int y)
            set(GridPoint Gridpoint, E obj)
            set(int x, int y, E obj)
        }

        class IndexedGrid~E~ {
            <<Interface>>
            add(E obj)
            add(int index, E obj)
            get(int index)
            remove(int index) E
            set(int index, E obj)
            indexOf(Object obj) int
            lastIndexOf(Object obj) int
            lastIndex() int
        }

        class UIGrid~E~ {

        }

        class Indexer {
            indexOf(GridPoint Gridpoint) int
            indexOf(int x, int y) int
        }
        

        Grid <|-- IndexedGrid
        IndexedGrid "1" --> "1" Indexer
        UIGrid --|> IndexedGrid
        Indexer <|-- ZigZagIndexer
        Indexer <|-- SpiralIndexer
        Indexer <|-- MortonIndexer